version: "3"
volumes:
  mariadb:
  snipe-it:
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb:latest
 #   container_name: snipe_mariadb
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=snipe
  snipeit:
    image: ghcr.io/linuxserver/snipe-it:latest
#    container_name: snipe-it
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - snipe-it:/config
    environment:
      - APP_URL=192.168.1.171:8080
      - MYSQL_PORT_3306_TCP_ADDR=mariadb
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=password123
      - PGID=1000
      - PUID=1000
    ports:
      - "8080:80"