version: '3.3'
services:
    webthings-gateway:
        devices:
            - '/dev/gpiomem:/dev/gpiomem'
        privileged: false
        ports:
            - '8080:8080'
            - '4443:4443'
        environment:
            - TZ=America/Los_Angeles
            - Country='United Kingdom'
            - Language='English'
        volumes:
            - '$PWD/webthings-gateway/data:/home/node/.mozilla-iot'
            - '/sys/class/gpio:/sys/class/gpio'
        network_mode: host
        logging:
           options:
               max-size: '1m'
               max-file: '5'
        container_name: webthings-gateway
        restart: unless-stopped
        image: 'webthingsio/gateway:latest'