version: '3.3'
services:
    webthings-gateway:
        devices:
            - '/dev/gpiomem:/dev/gpiomem'
        privileged: false
        devices:
            - '/dev/snd'
        
        ports:
            - '8080:8080'
            - '4443:4443'
            - '1900:1900/udp'
            - '554:554'
            - '554:554/udp'
        environment:
            - TZ=America/Los_Angeles
 # Country env variable doesnt appear to work.
 #           - Country='United Kingdom'
            - Language=English
        volumes:
            - '$PWD/data:/home/node/.mozilla-iot'
            - '/sys/class/gpio:/sys/class/gpio'
 # Uncomment below if you need access to alsa.conf
 #           - '/usr/share/alsa/alsa.conf:/usr/share/alsa/alsa.conf'
        network_mode: host
        logging:
           options:
               max-size: '1m'
               max-file: '5'
        container_name: webthings-gateway
        restart: unless-stopped
        image: 'webthingsio/gateway:latest'