version: "3"
services:
  radius:
    image: frauhottelmann/daloradius-docker:tag #you need to change the tag to your arch and the desired version
    container_name: radius
    restart: always
    depends_on:
      - "radius-mysql" 
    ports:
      - '1812:1812/udp'
      - '1813:1813/udp'
      - '80:80'
    environment:
      - MYSQL_HOST=radius-mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=dalodbpass
#    volumes:
#      - ./radius/clients.conf:/etc/freeradius/3.0/clients.conf
#      - ./radius/eap:/etc/freeradius/3.0/mods-available/eap
#      - ./ssl/fullchain.pem:/etc/freeradius/3.0/certs/fullchain.pem
#      - ./ssl/privkey.pem:/etc/freeradius/3.0/certs/privkey.pem
  radius-mysql:
    image: mariadb:10.3 # use image: linuxserver/mariadb:arm32v7-110.3.18mariabionic-ls37 for RaspberryPi
    container_name: radius-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=dalodbpass
      - MYSQL_ROOT_PASSWORD=dalorootpass
    volumes:
	- "./radius-mysql:/var/lib/mysql"