version: '3.3'
services:
    shairport-sync:
        restart: unless-stopped
        network_mode: host
        environment: 
            - NAME='McAirplay'
            - TZ='TZ=America/Los_Angeles'
        devices:
            - '/dev/snd:/dev/snd'
        volumes:
            - '/usr/share/alsa/alsa.conf:/usr/share/alsa/alsa.conf'
 #           - '$PWD/etc/shairport-sync.conf:/etc/shairport-sync.conf'
        container_name: shairport-sync
        image: mikebrady/shairport-sync