version: '2'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - $HOME/docker/home-assistant/config:/config
    environment:
      - TZ=America/Los_Angeles
    restart: unless-stopped
    ports:
      - 8123:8123