version: '2'

services:
  rpi-spotify:
    image: derkades/raspotify
    container_name: raspotify
    privileged: true
    network_mode: host
    devices: ['/dev/snd:/dev/snd']
    environment:
      SPOTIFY_NAME: 'raspotify'
      ALSA_SLAVE_PCM: 'plughw:1,0'
    restart: unless-stopped
#    volumes:
#      - /usr/share/alsa/alsa.conf:/usr/share/alsa/alsa.conf
