version: '2'

services:
  rpi-spotify:
    image: derkades/raspotify
    network_mode: host
    devices: ['/dev/snd:/dev/snd']
    environment:
      SPOTIFY_NAME: 'Spotify Connect'
    volumes:
      - /usr/share/alsa/alsa.conf:/usr/share/alsa/alsa.conf
