version: '2'
services:
    adguardhome:
        container_name: adguardhome
        volumes:
            - '$PWD/work:/opt/adguardhome/work'
            - '$PWD/conf:/opt/adguardhome/conf'
        ports:
            - '53:53/tcp'
            - '53:53/udp'
            - '80:80/tcp'
            - '3000:3000/tcp'
            - '67:67/udp'
            - '68:68/tcp'
            - '68:68/udp'
            - '443:443/tcp'
            - '853:853/tcp'
        image: adguard/adguardhome
