version: '2'

volumes:
  portainer
#  portainer-agent

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
#      - /etc/letsencrypt/archive/www.example.com:/certs:ro
#    command:
#      - --ssl
#      - --sslcert /certs/cert1.pem
#      - --sslkey /certs/privkey1.pem
    restart: always

#  portainer_agent:
#    image: portainer/agent
#    container_name: agent
#    ports:
#      - 9001:9001
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer-agent:/var/lib/docker/volumes
#    restart: always
